name: Build APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Ambil repo
    - name: Checkout
      uses: actions/checkout@v3

    # 2. SET PERMISSION DI SINI 🔥
    - name: Kasih izin gradlew
      run: chmod +x gradlew

    # 3. Setup Java
    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    # 4. Build APK
    - name: Build APK
      run: ./gradlew assembleDebug

    # 5. Upload hasil
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: TerorismePS
        path: app/build/outputs/apk/debug/app-debug.apk
